DefaultContentLanguage: 'fr'
languageCode: 'fr'

title: Club d‚Äôathl√©tisme Corsaire-Chaparral
baseURL: "https://corsaire-chaparral.org" # the base hostname & protocol for your site
theme: hugo-theme-coch
copyright: Tous droits r√©serv√©s.

publishDir: public

permalinks:
  nouvelles: nouvelles/:year/:month/:day/:slug

hrefTargetBlank: true

# Build pages with 'future' date
buildFuture: true

params:
  themeColor: '#f26e21'
  description: >
    Situ√© dans les Basses-Laurentides, le club d‚Äôathl√©tisme Corsaire-Chaparral est un organisme sans but lucratif dont la mission est de promouvoir l‚Äôathl√©tisme aupr√®s des jeunes.
  facebook: "CorsaireChaparral"
  twitter: "CorsaireC"
  instagram: "corsairechaparral"
  email: corsairechaparal@hotmail.com
  adminEmail: louis@corsaire-chaparral.org
  admin: Louis-Olivier Brassard
  stripePublicKey: pk_live_ccR6ujsv04d7TjBjRvVBgFvn
  apiUrl: https://api.corsaire-chaparral.org/v1/payment/new
#  annonce: >
#   Championnats 2019 Champs <a href="/resultats/direct/" class="btn btn-primary -sm">R√©sultats üî•</a>
#sectionPagesMenu: main


menu:
  main:
#  - identifier: home
#    title: Accueil
#    url: '/'
#    weight: -110
  
  - identifier: club
    title: Club
    url: '/club/'
    weight: 10
  - identifier: inscription
    parent: club
    title: Inscription
    url: '/inscription/'
    weight: 30
  - identifier: entrainements
    url: '/club/entrainements/'
    title: Entra√Ænements
    parent: club
    weight: 40
#  - identifier: inscription
#    url: '/club/inscription/'
#    title: Inscription
#    parent: club
  - identifier: entraineurs
    url: '/club/entraineurs/'
    title: Entra√Æneurs
    parent: club
    weight: 40
#  - identifier: liens-ressources
#    url: '/club/liens-ressources/'
#    title: Liens et ressources
#    parent: club
#  - identifier: records-statistiques
#    url: '/club/records-statistiques/'
#    title: Records et statistiques
#    parent: club

  - identifier: competitions
    title: Comp√©titions
    url: '/competitions/'
    weight: 20

  - identifier: nouvelles
    url: '/nouvelles/'
    title: Nouvelles
    weight: 40

#  - identifier: coch-invitation
#    title: Corsaire-Chaparral Invitation
#    url: '/competitions/corsaire-chaparral-invitation/'
#    weight: 0
#    parent: competitions
#  - identifier: challenge-andre-harel
#    title: Challenge Andr√©-Harel
#    url: '/competitions/challenge-andre-harel/'
#    weight: 0
#    parent: competitions
#  - identifier: crepuscules
#    title: Cr√©puscules
#    url: '/competitions/crepuscules/'
#    weight: 0
#    parent: competitions
#  - identifier: festival-jeunes
#    title: Festival en salle pour jeunes
#    url: '/competitions/festival-en-salle-pour-jeunes/'
#    weight: 0
#    parent: competitions
#  - identifier: challenge-jean-paul-baert
#    title: Challenge Jean-Paul-Baert
#    url: '/competitions/challenge-jean-paul-baert/'
#    weight: 0
#    parent: competitions
#  - identifier: finale-regionale
#    title: Finale r√©gionale des Jeux du Qu√©bec
#    url: '/competitions/finale-regionale/'
#    weight: 0
#    parent: competitions

#  - identifier: camp-de-jour-highlight
#    title: Camp de jour 2019
#    url: '/camp-de-jour/'
#    weight: 5
#    active: true
#  
#  - identifier: photos
#    title: Photos
#    url: '/photos/'
#    weight: 80
  
#  - identifier: partenaires
#    title: Partenaires
#    url: '/partenaires/'
#    weight: 90

#  - identifier: contact
#    title: Contact
#    url: '/contact/'
#    weight: 110
  membres:
#    - identifier: portail
#      title: Portail
#      url: http://portail.corsaire-chaparral.org/
#      weight: 10
    - identifier: formulaires
      title: Formulaires
      url: /club/liens-ressources/formulaires/
      weight: 10
    - identifier: photos
      title: Photos
      url: https://photos.corsaire-chaparral.org/
      weight: 20
    - identifier: fichiers
      title: Fichiers
      url: https://fichiers.corsaire-chaparral.org/
      weight: 30
    - identifier: discussions
      title: Discussions d‚Äô√©quipe
      url: https://framateam.org/coch/
      weight: 40
    - identifier: campagnes
      title: Communications
      url: https://campagnes.corsaire-chaparral.org/
      weight: 50
    - identifier: admin-cdj
      title: Gestion du camp de jour
      url: https://campdejour2019.corsaire-chaparral.org/
      weight: 60
    - identifier: activites
      title: Gestion des activit√©s
      url: https://activites.corsaire-chaparral.org/
      weight: 70
    - identifier: courriels
      title: Courriel web
      url: https://mail.corsaire-chaparral.org/
      weight: 80